"""create celery_task_table indexes update

Revision ID: 5e09321be2eb
Revises: bd7cd012ab5c
Create Date: 2026-06-21 00:14:34.608697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e09321be2eb'
down_revision: Union[str, Sequence[str], None] = 'bd7cd012ab5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_task_name_args_hash'), table_name='celery_task_execution')
    op.create_index('idx_task_name_id_args_hash', 'celery_task_execution', ['task_name', 'celery_task_id', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_name_id_args_hash', table_name='celery_task_execution')
    op.create_index(op.f('idx_task_name_args_hash'), 'celery_task_execution', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
